language: r
r:
  - release
r_binary_packages:
  - devtools
  - roxygen2
  - tidyverse
  - lubridate
notifications:
  email: false
script: |
  R CMD build .
  R CMD INSTALL analysr*.tar.gz
  R CMD check --as-cran --no-install analysr*.tar.gz
  cat analysr.Rcheck/00check.log
  Rscript -e "\
  testr <- devtools::test(); \
  testr <- as.data.frame(testr); \
  if(any(testr\$error) || any(testr\$warning > 0)) \
    stop('Found failing tests') \
  "